export { default as colors } from './colors'
export { default as fontSizes } from './fontSizes'
export { default as fontWeights } from './fontWeights'
export { default as lineHeights } from './lineHeights'
export { default as radius } from './radius'
export { default as zIndex } from './zIndex'

export type { ColorsType } from './colors'
export type { FontSizesType } from './fontSizes'
export type { FontWeightsType } from './fontWeights'
export type { LineHeightsType } from './lineHeights'
export type { RadiusType } from './radius'
export type { ZIndexType } from './zIndex'